### ISSUE TITLE
SPIKE the emailing situation and see if we can roll text messages in this

### ISSUE THREAD

**Issue by drteresavasquez** [Pencil-For-Schools/pencil-tech-admin#27]
Good article: https://www.courier.com/guides/python-send-sms/

This looks the most recent and promising: https://pypi.org/project/googlevoice/

Not sure if this still would work: 
- https://sphinxdoc.github.io/pygooglevoice/index.html
- EXAMPLES: https://sphinxdoc.github.io/pygooglevoice/examples.html

**Comment by Justin-Ferwerda** [comment]
Implemented Courier on a branch and shared details with design team to implement email designs.
