### ISSUE TITLE
Set Up Database Tables - Shopping App

### ISSUE THREAD

**Issue by drteresavasquez** [Pencil-For-Schools/pencil-tech-admin#7]
## **1. Set Up Database Tables**

- **Task 1: Configure `order` Table**
  - [ ] **Action:** Set up the `order` table to track orders placed by teachers.
  - **Details:**
    - Columns: 
      - `id` (Primary Key)
      - `teacher_id` (Foreign Key to `teacher`)
      - `pickup` (Boolean, indicating whether the order is for immediate pickup or pre-scheduled)
      - `created_at` (Timestamp when the order is created)
      - `fulfilled_at` (Timestamp when the order is fulfilled)
      - `approved` (Boolean, indicating if the order has been approved for processing)
    - This table will keep track of all the orders submitted by teachers and their fulfillment status.

- **Task 2: Configure `pencil_box_location_inventory_item_order` Table**
  - [ ] **Action:** Create a table to manage the items associated with each order.
  - **Details:**
    - Columns:
      - `id` (Primary Key)
      - `order_id` (Foreign Key to `order`)
      - `pencil_box_location_inventory_item_id` (Foreign Key to the inventory item at a specific location)
      - `qty` (Quantity of the item ordered)
    - This table links each item in the order to the specific inventory item and tracks quantities.

**Comment by JohnMDoll** [comment]
@TrinityChristiana, this looks good to me in dev:

![Image](https://github.com/user-attachments/assets/558bd288-cfb4-488d-aa6d-bb216da44a18)

![Image](https://github.com/user-attachments/assets/1e4039c7-2a57-4ff9-970b-824adc520509)
